apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: rujool11/core-service:v0.0   
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: NodePort
  selector:
    app: core-service
  ports:
    - port: 8002          # internal port
      targetPort: 8002    # container port
      nodePort: 30002     # external port (accessible via localhost:30002)
